/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Scheduler;

import Classes.Hall;
import Classes.IOMethods;
import Classes.Scheduler;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Hg
 */
public class Scheduler_addHall extends javax.swing.JFrame {

    private char hallType;
    DecimalFormat df = new DecimalFormat("#.##");
    Hall hall;
    private ArrayList<ArrayList<String>> hallList;
    private int page;
    private String userID;
    
    
    

    public Scheduler_addHall()
    {
        initComponents();
         //construct for testing purposes
        hall = new Hall();
        this.hallList = hall.getHallList();
    }
    
    
    /**
     * Creates new form scheduler_addHall
        @param hallType = halltype (A = Auditorium, B = banquet hall, C = conference room)
       @param hallList = all rows of text in hall.txt
       * @param page: return to the selected tab in tabbed pane when back button is clicked
       * @param userID = use to hold currentUserID when the mainPage is disposed, pass parameter to mainPage when going back
       
     */
    
    public Scheduler_addHall(int page,String userID,char hallType,ArrayList<ArrayList<String>> hallList) {
        initComponents();
        this.userID = userID;
        this.page = page;
        this.hallType = hallType;
        
        //set default value for price and capacity
        
        switch (hallType) 
        {
            case 'A' -> {
                hallTypeComboBox.setSelectedIndex(0);
                priceFormattedTextField.setValue(Hall.AUDIPRICE);
                capacitySpinner.setValue(1000);
            }
            case 'B' -> {
                hallTypeComboBox.setSelectedIndex(1);
                priceFormattedTextField.setValue(Hall.BANQUETPRICE);
                capacitySpinner.setValue(300);
            }
            case 'C' -> {
                hallTypeComboBox.setSelectedIndex(2);
                priceFormattedTextField.setValue(Hall.CONFROOMPRICE);
                capacitySpinner.setValue(30);
            }
            default -> System.out.println("Aww man...");
            
        }
        this.hallList = hallList;
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        btnAddHall = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldHallName = new javax.swing.JTextField();
        hallTypeComboBox = new javax.swing.JComboBox<>();
        priceFormattedTextField = new javax.swing.JFormattedTextField();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        capacitySpinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescription = new javax.swing.JTextArea();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(582, 484));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFocusable(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 550));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 550));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        btnAddHall.setBackground(new java.awt.Color(87, 114, 255));
        btnAddHall.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddHall.setForeground(new java.awt.Color(255, 255, 255));
        btnAddHall.setText("Add");
        btnAddHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHallActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Please upload an image");

        jButton1.setBackground(new java.awt.Color(87, 114, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(75, 75, 75))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(224, 251, 255));
        jPanel3.setForeground(new java.awt.Color(14, 251, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(600, 503));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("New Hall");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Hall Name");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Hall Type");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Rental Price per hour (RM)");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Description");

        hallTypeComboBox.setBackground(new java.awt.Color(255, 255, 255));
        hallTypeComboBox.setForeground(new java.awt.Color(0, 0, 0));
        hallTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auditorium", "Banquet Hall", "Conference Room" }));
        hallTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallTypeComboBoxActionPerformed(evt);
            }
        });

        priceFormattedTextField.setBackground(new java.awt.Color(255, 255, 255));
        priceFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        priceFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFormattedTextFieldActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(87, 114, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Capacity");

        capacitySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        textAreaDescription.setColumns(20);
        textAreaDescription.setLineWrap(true);
        textAreaDescription.setRows(5);
        jScrollPane1.setViewportView(textAreaDescription);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(140, 140, 140))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddHall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(textFieldHallName)
                            .addComponent(hallTypeComboBox, 0, 189, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(priceFormattedTextField)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(capacitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(91, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldHallName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hallTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(capacitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(btnAddHall, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHallActionPerformed
        // TODO add your handling code here:
        //logic for add new hall if passes all data validations
        
        //validate if the hall name exist to ensure names do not repeat
        
        boolean repeatedName = false;
        boolean noName = false;
        boolean multiLines = false;
        boolean priceIsZero = false;
        
        //validate if the textFieldHallName is empty (maximum 3 words)
        //regex pattern: Must start with alphabetical characters, maximum 3 words
        if (textFieldHallName.getText().length() == 0 || !textFieldHallName.getText().matches("^[a-zA-Z']+[ ]?[\\d]*[\\w]*[ ]?[\\d]*[\\w]*$"))
        {
            noName = true;
        }
        
        //catch if price is zero
        if (Double.parseDouble(priceFormattedTextField.getText())<=0)
        {
            priceIsZero=true;
        }
        
        //validate if hallName is repeated
        if (!hallList.isEmpty())
        {
            for (ArrayList<String> row: hallList)
            {
                if (textFieldHallName.getText().equals(row.get(1)))
                {
                    repeatedName = true;
                    break;
                }
            }
            
        }
        
        if (textAreaDescription.getText().contains("\n"))
        {
            multiLines = true;
        }
        
        if (!repeatedName && !noName &&!multiLines&&!priceIsZero)
        {
            
//            ArrayList<String> newHall = new ArrayList<>();
            Hall newhall = new Hall();
            newhall.setHallID(IOMethods.updateIndex("H", 5));
            //add hall name (stripped leading white space)
            newhall.setHallName(textFieldHallName.getText().strip());

            //return the first char of the hallType 
            String type = (String) hallTypeComboBox.getSelectedItem();
            char zero = type.charAt(0);
            newhall.setHallType(zero);

            //add price and description to arraylist
            newhall.setPricePerHour(Double.parseDouble(priceFormattedTextField.getText()));

            //add spinner value (capacity)
            int capacity = Integer.parseInt(capacitySpinner.getValue().toString());
            newhall.setCapacity(capacity);
            
            /*
            set default value "Description yet to be added" if no description
            is added
            */
            
            if (textAreaDescription.getText().length()==0)
            {
                
                newhall.setDescription("Description yet to be added");
            }
            else
            {
                newhall.setDescription(textAreaDescription.getText());
                
            }

            Scheduler scheduler = new Scheduler();
            //save arrayList
            scheduler.addHall(newhall.toStringArrayList());
            JOptionPane.showMessageDialog(null, "Hall \"" + textFieldHallName.getText() + "\" added to database.");
            
            //reset all fields
            textFieldHallName.setText("");
            textAreaDescription.setText("");
            textFieldHallName.grabFocus(); //set focus on textField
            hallTypeComboBox.setSelectedIndex(page);
            
            if (page==0)
            {
                priceFormattedTextField.setValue(Hall.AUDIPRICE);
            }
            else if (page ==1)
            {
                priceFormattedTextField.setValue(Hall.BANQUETPRICE);
                
            }
            else if (page == 2)
            {
                priceFormattedTextField.setValue(Hall.CONFROOMPRICE);
            }
            this.hallList = IOMethods.readFile(IOMethods.HALLTEXT); //reset the hallList
            
        }
        else if (repeatedName)
        {
            JOptionPane.showMessageDialog(null, "Hall name \"" + textFieldHallName.getText() + "\" already exists.\nPlease choose another name.");
            textAreaDescription.setText("");
            textFieldHallName.requestFocus();
            
        }
        else if (noName)
        {
            JOptionPane.showMessageDialog(null, "Please enter a valid hall name.\n (Maximum 3 words).");
            textFieldHallName.setText("");
            textFieldHallName.grabFocus();
            
        }
        else if (multiLines)
        {
            JOptionPane.showMessageDialog(null, "Please do not insert multi lines at description.");
            textAreaDescription.grabFocus();
            
        }
        else if (priceIsZero)
        {
            JOptionPane.showMessageDialog(null, "Price per hour cannot be zero.");
            
        }
        
    }//GEN-LAST:event_btnAddHallActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //new scheduler_mainPage().setVisible(true);
        new Scheduler_mainPageHardCode(userID,page);
    }//GEN-LAST:event_btnBackActionPerformed

    private void priceFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFormattedTextFieldActionPerformed

    private void hallTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallTypeComboBoxActionPerformed
        // TODO add your handling code here:
        
        //set default value for 
        switch (hallTypeComboBox.getSelectedIndex()) {
            case 0:
                priceFormattedTextField.setValue(Hall.AUDIPRICE);
                capacitySpinner.setValue(1000);
                break;
            case 1:
                priceFormattedTextField.setValue(Hall.BANQUETPRICE);
                capacitySpinner.setValue(300);
                break;
            case 2:
                priceFormattedTextField.setValue(Hall.CONFROOMPRICE);
                capacitySpinner.setValue(30);
                break;
            default:
                System.out.println("Aww man....");
        }
    }//GEN-LAST:event_hallTypeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scheduler_addHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scheduler_addHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scheduler_addHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scheduler_addHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scheduler_addHall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHall;
    private javax.swing.JButton btnBack;
    private javax.swing.JSpinner capacitySpinner;
    private javax.swing.JComboBox<String> hallTypeComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField priceFormattedTextField;
    private javax.swing.JTextArea textAreaDescription;
    private javax.swing.JTextField textFieldHallName;
    // End of variables declaration//GEN-END:variables
}
