/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Scheduler;

import Classes.Scheduler;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hg
 */
public class TaskDisplayer extends javax.swing.JPanel {

    /**
     * Creates new form TaskDisplayer
     */
    
    private String reportID;
    private String bookingID;
    private String description;
    private String status;
    private String userID;
    private String date;
    private ArrayList<ArrayList<String>> bookingList;
    private ArrayList<ArrayList<String>> hallList;
    private JFrame frame;

    public TaskDisplayer() {
        initComponents();
    }
    
    public TaskDisplayer(ArrayList<String>task, JFrame frame) 
    {
        initComponents();
        this.frame = frame;
        this.reportID = task.get(0);
        this.bookingID = task.get(1);
        this.description = task.get(2);
        this.status = task.get(3);
        this.userID = task.get(4);
        this.date = task.get(5);
        
        //clear existing item Listeners
        for (ItemListener listener : comboBoxStatus.getItemListeners()) 
        {
             comboBoxStatus.removeItemListener(listener);
        }
        
        labelIssue.setText("Issue: " + description);
        labelAssignDate.setText("Assigned Date: " + date);
        comboBoxStatus.setSelectedItem(status);
        
        
        //item listeners to handle change events in combo Box
        comboBoxStatus.addItemListener(evt -> {
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                comboBoxStatusItemStateChanged(evt);
            }
        });
        
    }

    
        private void comboBoxStatusItemStateChanged(ItemEvent evt){
        this.status = evt.getItem().toString();  // Get the selected item

        // Example scheduler and method call
        Scheduler scheduler = new Scheduler();
        scheduler.changeMaintenanceStatus(this.reportID, this.status);
            JOptionPane.showMessageDialog(null, "Status changed!!");
        
        if (evt.getItem().toString().equals("done"))
        {
            frame.dispose();
            new Scheduler_mainPageHardCode(userID,3);
        }

        // Closing current frame and showing message

        // Open new main page
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelAssignDate = new javax.swing.JLabel();
        labelIssue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        comboBoxStatus = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        labelAssignDate.setText("jLabel2");

        labelIssue.setText("jLabel3");

        jLabel4.setText("Status:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        comboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pending", "scheduled", "done" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 370, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAssignDate)
                    .addComponent(labelIssue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelAssignDate)
                .addGap(18, 18, 18)
                .addComponent(labelIssue)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        comboBoxStatus.addItemListener(new ItemListener() {

            public void itemStateChanged(ItemEvent evt) {
                if (evt.getStateChange() == ItemEvent.SELECTED) {
                    comboBoxStatusItemStateChanged(evt);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxStatus;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAssignDate;
    private javax.swing.JLabel labelIssue;
    // End of variables declaration//GEN-END:variables
}
